### ISSUE TITLE
Need to update react-router-dom version to 6

### ISSUE THREAD

**Issue by David-YuWei** [CBIIT/bento-frontend#865]
In order to use Routes instead of HashRoute to remove the # from the browser url.
Prefer to have https://ccdi.cancer.gov/ instead of https://ccdi.cancer.gov/#/

**Comment by iksheth** [comment]
@n2iw Looks like @David-YuWei have published "[1.0.0-ccdihub.1](https://www.npmjs.com/package/@bento-core/authentication/v/1.0.0-ccdihub.1)". 

When I am running "npm i @bento-core/authentication" it fetches 1.0.0-ccdihub.1 version for @bento-core/authentication and also [1.0.0-ccdihub.1](https://www.npmjs.com/package/@bento-core/authentication/v/1.0.0-ccdihub.1?activeTab=versions) listed as latest for @bento-core/authentication.

**Comment by iksheth** [comment]
Resolved Closing.
